"""01_before_relation-db

Revision ID: 1549875fc8fa
Revises: cda09b92bef5
Create Date: 2022-12-24 18:33:24.927632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1549875fc8fa'
down_revision = 'cda09b92bef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
