"""06_relation-db

Revision ID: 437c1ca003ec
Revises: 97e21149aeac
Create Date: 2022-12-24 19:43:57.299619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437c1ca003ec'
down_revision = '97e21149aeac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('urls_list', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'urls', ['urls_list'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'urls_list')
    # ### end Alembic commands ###
