"""06_initial-db

Revision ID: 6be756d6694c
Revises: ec024e388225
Create Date: 2022-12-22 23:45:18.756729

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6be756d6694c'
down_revision = 'ec024e388225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('usage_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'usage_count')
    # ### end Alembic commands ###
