"""1_private_url

Revision ID: 79fa3185a7fe
Revises: feb2910b2683
Create Date: 2022-12-24 20:23:43.664429

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '79fa3185a7fe'
down_revision = 'feb2910b2683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_private')
    # ### end Alembic commands ###
