"""12_initial-db

Revision ID: 7c36a6d9d8dc
Revises: e4c86088d551
Create Date: 2022-12-24 17:13:10.750664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c36a6d9d8dc'
down_revision = 'e4c86088d551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('urls_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'urls', ['urls_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'urls_id')
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
