"""09_initial-db

Revision ID: 8b7649d2fffb
Revises: d1bb3c2ccb47
Create Date: 2022-12-23 00:28:47.399603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7649d2fffb'
down_revision = 'd1bb3c2ccb47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'private')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
