"""02_relation-db

Revision ID: 9561c3031aa9
Revises: 1549875fc8fa
Create Date: 2022-12-24 18:44:23.978579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9561c3031aa9'
down_revision = '1549875fc8fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'urls', 'users', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_column('urls', 'author')
    # ### end Alembic commands ###
