"""04_relation-db

Revision ID: 97e21149aeac
Revises: ac86f6bd4247
Create Date: 2022-12-24 18:51:03.268602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e21149aeac'
down_revision = 'ac86f6bd4247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
