"""2_relation

Revision ID: a545cd8de433
Revises: 437c1ca003ec
Create Date: 2022-12-24 19:49:23.754228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a545cd8de433'
down_revision = '437c1ca003ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_author_fkey', 'urls', type_='foreignkey')
    op.drop_column('urls', 'author')
    op.drop_constraint('users_urls_list_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'urls_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('urls_list', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_urls_list_fkey', 'users', 'urls', ['urls_list'], ['id'])
    op.add_column('urls', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('urls_author_fkey', 'urls', 'users', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
