"""03_relation-db

Revision ID: ac86f6bd4247
Revises: 9561c3031aa9
Create Date: 2022-12-24 18:47:57.050953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac86f6bd4247'
down_revision = '9561c3031aa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
