"""15_initial-db

Revision ID: cda09b92bef5
Revises: c1455ae0f3c0
Create Date: 2022-12-24 18:32:23.371014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda09b92bef5'
down_revision = 'c1455ae0f3c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_author_fkey', 'urls', type_='foreignkey')
    op.drop_column('urls', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('urls_author_fkey', 'urls', 'users', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
