"""10_initial-db

Revision ID: d06e454d8bf1
Revises: 8b7649d2fffb
Create Date: 2022-12-23 03:01:22.033283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06e454d8bf1'
down_revision = '8b7649d2fffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_archived')
    # ### end Alembic commands ###
