"""08_initial-db

Revision ID: d1bb3c2ccb47
Revises: f8618494cfa5
Create Date: 2022-12-23 00:07:55.513095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd1bb3c2ccb47'
down_revision = 'f8618494cfa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
