"""05_initial-db

Revision ID: ec024e388225
Revises: fb37778af131
Create Date: 2022-12-22 22:09:16.810257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec024e388225'
down_revision = 'fb37778af131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
