"""02_initial-db

Revision ID: ec781b7c28cb
Revises: 19752097177e
Create Date: 2022-12-22 20:58:01.651862

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec781b7c28cb'
down_revision = '19752097177e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'created_at')
    # ### end Alembic commands ###
