"""04_initial-db

Revision ID: fb37778af131
Revises: 033b9f17f6f7
Create Date: 2022-12-22 22:08:48.143481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb37778af131'
down_revision = '033b9f17f6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
